load('@bazel_tools//tools/build_defs/repo:git.bzl', 'git_repository')
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

local_repository(
  name = "mylib",
  path = "../../../mylib"
)

local_repository(
  name = "third_party",
  path = "../../../third_party/output"
)
